AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Rift Rewind - League of Legends Recap Generator

Parameters:
  AmplifyDomain:
    Type: String
    Default: 'https://main.d6pa54tf54cr.amplifyapp.com'
    Description: Your Amplify app domain for CORS (update after deployment)
    
  RiotApiKeyParameter:
    Type: String
    Default: '/rift-rewind/riot-api-key'
    Description: SSM Parameter Store path for Riot API key

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.12
    Architectures:
      - x86_64

Resources:
  # S3 Bucket for storing match data
  MatchDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'rift-rewind-match-data-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      Tags:
        - Key: Project
          Value: rift-rewind
        - Key: Purpose
          Value: match-data-storage

  # IAM Role for Lambda functions
  RiftRewindLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SSMParameterAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${RiotApiKeyParameter}'
        - PolicyName: S3MatchDataAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt MatchDataBucket.Arn
                  - !Sub '${MatchDataBucket.Arn}/*'
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: '*'
      Tags:
        - Key: Project
          Value: rift-rewind

  # Test Lambda Function with Function URL
  TestRiotApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: test-riot-api
      CodeUri: lambda/test-riot-api/
      Handler: lambda_function.lambda_handler
      Description: Test Riot API connectivity and data retrieval
      Role: !GetAtt RiftRewindLambdaRole.Arn
      Environment:
        Variables:
          MATCH_DATA_BUCKET: !Ref MatchDataBucket
          RIOT_API_KEY_PARAM: !Ref RiotApiKeyParameter
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'  # Allow everything for quick iteration
          AllowHeaders:
            - Content-Type
          AllowMethods:
            - POST
          MaxAge: 300
      Tags:
        Project: rift-rewind
        Environment: dev

  # Process Matches Lambda Function with Function URL
  ProcessMatchesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: process-matches
      CodeUri: lambda/process-matches/
      Handler: lambda_function.lambda_handler
      Description: Process raw match data into clean stats CSV
      Role: !GetAtt RiftRewindLambdaRole.Arn
      Environment:
        Variables:
          MATCH_DATA_BUCKET: !Ref MatchDataBucket
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'  # Allow everything for quick iteration
          AllowHeaders:
            - Content-Type
          AllowMethods:
            - POST
          MaxAge: 300
      Tags:
        Project: rift-rewind
        Environment: dev

  # Query RAG Lambda Function with Function URL
  QueryRAGFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: query-rag
      CodeUri: lambda/query-rag/
      Handler: lambda_function.lambda_handler
      Description: Query match data using Amazon Bedrock RAG
      Role: !GetAtt RiftRewindLambdaRole.Arn
      Timeout: 60
      Environment:
        Variables:
          MATCH_DATA_BUCKET: !Ref MatchDataBucket
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'  # Allow everything for quick iteration
          AllowHeaders:
            - Content-Type
          AllowMethods:
            - POST
          MaxAge: 300
      Tags:
        Project: rift-rewind
        Environment: dev

Outputs:
  FunctionUrl:
    Description: Function URL endpoint for test-riot-api
    Value: !GetAtt TestRiotApiFunctionUrl.FunctionUrl
    Export:
      Name: !Sub '${AWS::StackName}-FunctionUrl'

  ProcessMatchesFunctionUrl:
    Description: Function URL endpoint for process-matches
    Value: !GetAtt ProcessMatchesFunctionUrl.FunctionUrl
    Export:
      Name: !Sub '${AWS::StackName}-ProcessMatchesFunctionUrl'

  QueryRAGFunctionUrl:
    Description: Function URL endpoint for query-rag (Bedrock RAG)
    Value: !GetAtt QueryRAGFunctionUrl.FunctionUrl
    Export:
      Name: !Sub '${AWS::StackName}-QueryRAGFunctionUrl'

  MatchDataBucketName:
    Description: S3 bucket name for storing match data
    Value: !Ref MatchDataBucket
    Export:
      Name: !Sub '${AWS::StackName}-MatchDataBucket'

  AmplifyDomainUsed:
    Description: Amplify domain configured in CORS
    Value: !Ref AmplifyDomain